branches:
  only:
    - master

language: cpp

script-anchors:
  - &script-macOS
    - cd $TRAVIS_BUILD_DIR
    - mkdir build
    - cd build
    - cmake --version
    - cmake .. -GXcode -DTCC_BUILD_PLAYGROUND=OFF -DTCC_BUILD_BENCHMARK=OFF -DCMAKE_BUILD_TYPE:STRING=Release
    - cmake --build .
    - ctest

  - &script-linux-release
    - cd $TRAVIS_BUILD_DIR
    - mkdir build && cd build
    - cmake -GNinja -DCMAKE_BUILD_TYPE:STRING=Release -DTCC_BUILD_PLAYGROUND=OFF -DTCC_BUILD_BENCHMARK=OFF ..
    - cmake --build .
    - ctest

  - &script-linux-sanitizers
    - cd $TRAVIS_BUILD_DIR
    - mkdir build_Debug && cd build_Debug
    - cmake -GNinja -DCMAKE_BUILD_TYPE:STRING=Debug -DTCC_BUILD_PLAYGROUND=OFF -DTCC_BUILD_BENCHMARK=OFF -DTCC_BUILD_ASAN=ON -DTCC_BUILD_UBSAN=ON ..
    - cmake --build .
    - ctest

  - &script-linux-coverage
    - cd $TRAVIS_BUILD_DIR
    - export PATH=./scripts:$PATH
    - cmake -H. -GNinja -Bbuild -DTCC_BUILD_COVERAGE=ON
    - cd build && cmake --build .
    - cd build && lcov --gcov-tool llvm-gcov.sh -c -i -d . --base-directory . -o base_cov.info
    - cd build && ctest
    - cd build && lcov --gcov-tool llvm-gcov.sh -c -d . --base-directory . -o test_cov.info
    - cd build && lcov --gcov-tool llvm-gcov.sh -a base_cov.info -a test_cov.info -o cov.info
    - cd build && lcov --gcov-tool llvm-gcov.sh --remove cov.info "*boost/*" -o cov.info
    - cd build && lcov --gcov-tool llvm-gcov.sh --remove cov.info "*3rd_party/*" -o cov.info
    - cd build && lcov --gcov-tool llvm-gcov.sh --remove cov.info "*c++*" -o cov.info
    - cd build && lcov --gcov-tool llvm-gcov.sh --remove cov.info "*v1*" -o cov.info
    - cd build && lcov --gcov-tool llvm-gcov.sh --remove cov.info "*Xcode.app*" -o cov.info
    - bash <(curl -s https://codecov.io/bash) -f build/cov.info

matrix:
  include:
    - os: osx
      osx_image: xcode12
      addons:
        homebrew:
          casks:
            - cmake
            - boost@1.72
      script: *script-macOS

    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - sourceline: "ppa:mhier/libboost-latest"
            - ubuntu-toolchain-r-test
          packages:
            - g++-10
            - ninja-build
            - libboost1.73-dev
            - lcov
      env:
        - MATRIX_EVAL="CC=gcc-10 CXX=g++-10"
      script: *script-linux-release

    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - sourceline: "ppa:mhier/libboost-latest"
            - sourceline: "ppa:ubuntu-toolchain-r/test"
            - sourceline: "deb https://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main"
              key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
          packages:
            - ninja-build
            - libboost1.73-dev
            - clang++-10
            - lcov
      env:
        - MATRIX_EVAL="CC=clang-10 && CXX=clang++-10"
      script: *script-linux-sanitizers

    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - sourceline: "ppa:mhier/libboost-latest"
            - sourceline: "ppa:ubuntu-toolchain-r/test"
            - sourceline: "deb https://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main"
              key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
          packages:
            - ninja-build
            - libboost1.73-dev
            - clang++-10
            - lcov
      env:
        - MATRIX_EVAL="CC=clang-10 && CXX=clang++-10"
      script: *script-linux-coverage

before_install:
  - eval "${MATRIX_EVAL}"
