branches:
  only:
    - master

language: cpp

script-anchors:
  - &script-linux
    - cd $TRAVIS_BUILD_DIR
    - mkdir build && cd build
    # COVERAGE
    - cmake -GNinja -DTCC_BUILD_COVERAGE=ON -DTCC_BUILD_BENCHMARK=OFF ..
    - cmake --build .
    - ctest
    - bash <(curl -s https://codecov.io/bash) -x /usr/bin/gcov-7

matrix:
  include:
    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - sourceline: "ppa:mhier/libboost-latest"
            - sourceline: "ppa:ubuntu-toolchain-r/test"
          packages:
            - ninja-build
            - libboost1.70-dev
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
      script: *script-linux

before_install:
  - eval "${MATRIX_EVAL}"
