branches:
  only:
    - master

language: cpp

script-anchors:
  - &script-linux
    - cd $TRAVIS_BUILD_DIR
    - mkdir build && cd build
    # COVERAGE
    - cmake -GNinja -DTCC_BUILD_COVERAGE=ON ..
    - cmake --build .
    - ctest
    - bash <(curl -s https://codecov.io/bash) -x /usr/bin/gcov-7

matrix:
  include:
    - os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - ninja-build
      env:
        - MATRIX_EVAL="CC=gcc && CXX=g++"
      script: *script-linux

before_install:
  - eval "${MATRIX_EVAL}"
