branches:
  only:
    - master

language: cpp

script-anchors:
  - &script-macOS
    - cd $TRAVIS_BUILD_DIR
    - mkdir build
    - cd build
    - cmake .. -DTCC_BUILD_PLAYGROUND=OFF -DTCC_BUILD_BENCHMARK=OFF -DCMAKE_BUILD_TYPE:STRING=Release
    - cmake --build .
    - ctest

  - &script-linux-release
    - cd $TRAVIS_BUILD_DIR
    - mkdir build_release && cd build_release
    - cmake -GNinja -DCMAKE_BUILD_TYPE:STRING=Release -DTCC_BUILD_PLAYGROUND=OFF -DTCC_BUILD_BENCHMARK=OFF ..
    - cmake --build .
    - ctest

  - &script-linux-coverage
    - cd $TRAVIS_BUILD_DIR
    - mkdir build_coverage && cd build_coverage
    - cmake -GNinja -DTCC_BUILD_COVERAGE=ON -DTCC_BUILD_PLAYGROUND=OFF -DTCC_BUILD_BENCHMARK=OFF ..
    - cmake --build .
    - ./tcc/tcc
    - ./tcvm/tcvm
    - ctest
    - bash <(curl -s https://codecov.io/bash) -x /usr/bin/gcov-7

matrix:
  include:
    - os: osx
      osx_image: xcode11.2
      addons:
        homebrew:
          casks:
            - cmake
      script: *script-macOS

    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - sourceline: "ppa:mhier/libboost-latest"
            - sourceline: "ppa:ubuntu-toolchain-r/test"
            - sourceline: "deb https://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main"
              key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
          packages:
            - ninja-build
            - libboost1.70-dev
            - clang++-9
      env:
        - MATRIX_EVAL="CC=clang-9 && CXX=clang++-9"
      script: *script-linux-release

    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - sourceline: "ppa:mhier/libboost-latest"
          packages:
            - ninja-build
            - libboost1.70-dev
      env:
        - MATRIX_EVAL="CC=gcc && CXX=g++"
      script: *script-linux-coverage

before_install:
  - eval "${MATRIX_EVAL}"
