version: 0.1.0.{build}
branches:
  only:
    - master

image: Visual Studio 2017
platform: x64

environment:
  BOOST_ROOT: C:/Libraries/boost_1_69_0
  BOOST_LIBRARYDIR_WIN64: C:/Libraries/boost_1_69_0/lib64-msvc-14.1

clone_folder: C:/projects/tcc

configuration:
  - Release

install:
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive

build:
  parallel: true

build_script:
  - cd C:/projects/tcc
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 15 2017 Win64"
    -DTCC_BUILD_BENCHMARK=OFF
    -DTCC_BUILD_PLAYGROUND=OFF
    -DBOOST_ROOT="%BOOST_ROOT%"
    -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR_WIN64%"
    -DBoost_USE_STATIC_LIBS="ON"
    ..
  - cmake --build . --config Release
  - ctest
